/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as WorksProjectIdRouteImport } from './routes/works/$projectId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksProjectIdRoute = WorksProjectIdRouteImport.update({
  id: '/works/$projectId',
  path: '/works/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/works/$projectId': typeof WorksProjectIdRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/works/$projectId': typeof WorksProjectIdRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/works/$projectId': typeof WorksProjectIdRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/works/$projectId' | '/works/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/works/$projectId' | '/works'
  id: '__root__' | '/' | '/about' | '/works/$projectId' | '/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  WorksProjectIdRoute: typeof WorksProjectIdRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$projectId': {
      id: '/works/$projectId'
      path: '/works/$projectId'
      fullPath: '/works/$projectId'
      preLoaderRoute: typeof WorksProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  WorksProjectIdRoute: WorksProjectIdRoute,
  WorksIndexRoute: WorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
